# Generated by Django 3.0.5 on 2020-04-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200429_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=None, help_text='Ник', max_length=100),
            preserve_default=False,
        ),
    ]
