# Generated by Django 3.0.5 on 2020-06-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/photo/user_default.jpeg', null=True, upload_to=''),
        ),
    ]
